### PR TITLE
Cordova 10012020 465, 601, 604, 605

### PR DESCRIPTION
**Pull request by codinronan**
This is a bug fix update.

Update iOS SDK to 0.31.1
Update Android SDK to 4.2.1
Remove use_frameworks from Pod install
Remove addition of entitlements files, use existing ones instead & delete JS scripts that were creating them

Known issues:
iOS command line build seems to work provided ALL dependencies are updated and after use_frameworks was removed:
  node 10.15
  cordova: 9.0.0
  cordova-ios: 5.1.1
  branch: 4.0.1
  CocoaPods: 1.8.4

The test app in use demonstrating this version in action is here:
https://github.com/engineerapart/branch-cordova-helloworld

It uses my own published npm package name but the code is identical to what is being submitted here.

Relevant tickets:
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/465
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/610
  (and the related PR https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/575)
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/606
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/605
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/604
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/601

### CODE REVIEW

**Comment by codinronan** [comment]
Checking on Ionic 4 is in progress. Give me a bit and I'll update that here as well.

**Comment by adrianyg7** [comment]
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/554#issuecomment-576490067

**Comment by codinronan** [comment]
Ionic 4 with Capacitor is also working: 
https://github.com/engineerapart/branch-ionic-capacitor-helloworld

**Comment by echo-branch** [comment]
Looks good.  Going to merge to staging for further QA.

**Pull request merged**
