### PR TITLE
Deprecate delay for apple search ads method SDK-884

### PR DESCRIPTION
**Pull request by adrianyg7**
Deprecate delay for apple search ads method SDK-884

### CODE REVIEW

**Comment by romandragan** [comment]
@adrianyg7, @echo-branch, why it was deprecated? Is the a new way to track Search Ads in Cordova app?

**Comment by felipeclopes** [comment]
@romandragan +1

**Comment by echo-branch** [comment]
This was deprecated cause it does not work. The issue is that Apple Search Ads must be checked early in the application lifecycle to properly be handled by Branch.  This is not possible with Cordova's slow startup time.

The current way to handle this is making the equivalent call from within the iOS native code. In a future release, we plan on enabling it via a config file so early lifecycle settings can be properly handled by Cordova.

**Comment by romandragan** [comment]
@echo-branch, thank you, it would be super cool to have it as automated things configured via config, so it would be not necessary to edit delegate source every time.

**Pull request merged**
