### PR TITLE
Remove custom entitlement overrides

### LINKED ISSUE #465: Issue with Missing Push Notification Entitlement
Hello guys,

i wanted to start to use branch.io with my ionic app. I added it and on of course it works. But since i add the sdk, on every build i submit to the itunes store there comes an error from the app store:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app, "Mein Hetzner". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 

After some debugging with the ionic dev team, it turns out, that this sdk has the same problem described here: https://ionic.zendesk.com/hc/en-us/articles/360001923973?input_string=ios+builds+-+missing+push+entitlement

Can you have a look into this? I must remove the sdk from the app since i can't release the app on ios with it :)

Thank you!

### PR DESCRIPTION
**Pull request by Harjot1Singh**
Removes the new entitlement files that are written by the plugin, causing any existing entitlements that are modified in the standard `*-Entitlements.plist` to be ignored, breaking other plugins.

Fixes #465

### CODE REVIEW

**Comment by Textras** [comment]
hoping to see this merged.

**Comment by bobrosoft** [comment]
@echo-branch when that can be resolved? That's too critical for non-trivial apps

**Comment by echo-branch** [comment]
@bobrosoft 
We finally have new Cordova maintainers that are working on a new release which will address this.  Really sorry about the long delay.

**Comment by echo-branch** [comment]
This should be resolved in the latest release.

**Pull request closed without merging**
